nthread: 12
raw_data: 'rawdata'
metadata: 'metadata'
gene_signatures: 'rawdata/gene_signatures'
proc_data: 'procdata'
output: 'latest'
psets: ['GDSC_v1', 'GDSC_v2', 'CTRPv2', 'FIMM', 'gCSI', 'GRAY', 'CCLE', 
  'UHNBreast', 'PRISM', 'NCI60']
db_name: 'pharmacodb_test1'
meta_analysis_dir: 'rawdata/gene_signatures/metaanalysis'
write_db: true
